name: plantare_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.5
  firebase_core: ^2.32.0
  flutter:
    sdk: flutter
  intl: ^0.18.0
  cupertino_icons: ^1.0.6
  sqflite: ^2.4.0
  path: ^1.8.3
  google_fonts: ^4.0.3


dev_dependencies:
  cloud_firestore: ^4.17.5
  firebase_core: ^2.32.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  

flutter:
  uses-material-design: true

  assets:
    - assets/artigos.json
    - assets/images/onboarding_image.png
    - assets/images/seed_icon.png
    - assets/images/leaf_icon_red.png
    - assets/images/flower_icon_pink.png
    - assets/images/leaf_icon_yellow.png
    - assets/images/leaf_icon_green.png
    - assets/images/community_icon.png
    - assets/images/planting_bag.png
    - assets/images/watering_icon.png
    - assets/images/metrics_icon.png
    - assets/images/logo.png

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Black.ttf
        - asset: assets/fonts/Outfit-Bold.ttf
        - asset: assets/fonts/Outfit-ExtraBold.ttf
        - asset: assets/fonts/Outfit-ExtraLight.ttf
        - asset: assets/fonts/Outfit-Light.ttf
        - asset: assets/fonts/Outfit-Medium.ttf
        - asset: assets/fonts/Outfit-Regular.ttf
        - asset: assets/fonts/Outfit-SemiBold.ttf
        - asset: assets/fonts/Outfit-Thin.ttf